// Drive index.html in a real browser; compare what it prints with results.json. Node + playwright.
import { createRequire } from 'module'; import path from 'path'; import fs from 'fs'; import { fileURLToPath } from 'url';
const require = createRequire('/opt/node-tools/node_modules/'); const { chromium } = require('playwright');
const here = path.dirname(fileURLToPath(import.meta.url)); let bad = 0;
const R = JSON.parse(fs.readFileSync(path.join(here, 'results.json')));
const ok = (c, m) => { console.log((c ? 'ok   ' : 'FAIL ') + m); if (!c) bad++; };
const br = await chromium.launch({ executablePath: process.env.CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const pg = await br.newPage({ viewport: { width: 390, height: 900 } }); const errs = [];
pg.on('pageerror', e => errs.push(String(e))); pg.on('console', m => m.type() === 'error' && errs.push(m.text()));
await pg.goto('file://' + path.join(here, 'index.html'));
const f = (x, d) => x.toFixed(d);
const A = R.classes.all_odd.plain, K = R.by_k;
let t = await pg.innerText('#s1');
ok(t.includes('5 odd of 135') && t.includes(f(A[0].pred0, 3)) && t.includes(f(A[20].pred0, 3)) && t.includes(f(K[5].ratio_plain, 2)), 'browser: all five odd, a0 1 -> predictive and ratio match results.json');
t = await pg.innerText('#s2'); const u = A[20].unread_count;
ok(t.includes('median ' + u.median) && t.includes(u.lo + ' to ' + u.hi), 'browser: unread count at a0 = 1 matches (' + u.lo + ',' + u.median + ',' + u.hi + ')');
await pg.uncheck('#c_none'); await pg.uncheck('#c_unc'); t = await pg.innerText('#s1');
ok(t.includes('1 odd of 135') && t.includes(f(K[1].ratio_plain, 2)) && t.includes('one population'), 'browser: bone alone -> ratio ' + f(K[1].ratio_plain, 2) + ', leans to one population');
await pg.check('#c_none'); t = await pg.innerText('#s1'); ok(t.includes(f(K[3].ratio_plain, 2)), 'browser: bone + no-animal -> ' + f(K[3].ratio_plain, 2));
await pg.check('#c_unc'); await pg.fill('#rho', '0.05'); t = await pg.innerText('#s1');
ok(t.includes('Factor for strangers over one population: ' + f(K[5].ratio_discounted, 2)), 'browser: rho 0.05 -> ratio near ' + f(K[5].ratio_discounted, 2) + ' (page: ' + (t.match(/Factor[^.]*?<?b?>?([0-9.]+)/) || [])[1] + ')');
await pg.fill('#a0', '0'); t = await pg.innerText('#s2'); const u0 = R.classes.all_odd.discounted[0].unread_count;
ok(t.includes('median ' + u0.median), 'browser: a0 = 0, rho 0.05 -> median ' + u0.median);
ok(await pg.locator('#bars rect').count() === 6, 'browser: six bars');
ok(await pg.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'no horizontal scroll at 390 px');
await pg.setViewportSize({ width: 1100, height: 900 }); ok(await pg.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'no horizontal scroll at 1100 px');
ok(errs.length === 0, 'no console or page errors ' + errs.join('|'));
await pg.screenshot({ path: '/tmp/claude-0/s/c5s2.png', fullPage: true });
await br.close(); process.exit(bad ? 1 : 0);
