#!/usr/bin/env python3
"""Build the gold label set returned to the commissioning practice.

The labels below are the study's actual work product: one relation, one
rationale, one decider and (where the tie-break fired) one runner-up per case,
made by reading the sixty excerpts in `commission.v2.json` against the criteria
in `mb-cls-criteria.v2.json` and nothing else.

The script exists so the set is rebuildable and the labels are readable as a
table rather than buried in generated JSON. It reads the commission for excerpt
text and hashes — it never re-derives them — and it refuses to emit a set whose
case ids do not match the commission exactly.

Usage:  python3 projects/2026-08-01-sixty-cases-blind/build_label_set.py [--check]

Ulysses, 2026-08-01.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COMMISSION = ROOT / "docs/research-notes/meridian-commission/commission.v2.json"
CRITERIA = ROOT / "docs/research-notes/meridian-commission/mb-cls-criteria.v2.json"
OUT = ROOT / "docs/research-notes/meridian-commission/mb-cls-ulysses-v1.json"

# The moment the sixtieth rationale was written, recorded as it stood.
# See the return letter: this is BEFORE the criteria's own `locked_at`
# (2026-08-01T21:30:00Z) and will therefore fail the commissioner's order gate.
# It is not moved. A timestamp that passes a gate it did not meet is a fabrication.
LABELLED_AT = "2026-08-01T20:52:00Z"

# case_id suffix -> (relation | None, decided_by, tie_with, rationale_or_reason)
# `None` relation means undecidable; the fourth field is then the reason.
LABELS: dict[str, tuple[str | None, str, str | None, str]] = {
    "2205.08794": (
        "qualifies", "qualifies definition", None,
        "A Verifier separate from the Generator scores the generator's output, but the "
        "source's evidence reaches only logical-reasoning pre-training of language models "
        "and no stage of a research cycle, so the claim is narrowed rather than asserted.",
    ),
    "2402.00559": (
        "contextualizes", "contextualizes definition", None,
        "The source builds a benchmark measuring how well automatic verifiers judge "
        "reasoning chains, which bears on verification quality but takes no position on "
        "whether an automating system's checker is separate from its producer.",
    ),
    "2407.00466": (
        "contextualizes", "R-own-evidence", None,
        "The agent task checks facts in an external knowledge graph rather than the system's "
        "own outputs, and the remark about evaluating agents by asking the LLM itself reports "
        "others' practice, which R-own-evidence puts at most in contextualizes.",
    ),
    "2407.18367": (
        "contextualizes", "contextualizes definition", None,
        "The method verifies external claims against evidence, not the outputs of the system "
        "that produced them, so it bears on the subject matter without taking a position.",
    ),
    "2408.06292": (
        "contradicts", "contradicts definition (self-review clause)", None,
        "The source's own system completes the research cycle and then judges its own papers "
        "with an automated reviewer it built and runs, which the criteria count as self-review "
        "and therefore as a denial of independence.",
    ),
    "2409.04109": (
        "contradicts", "contradicts definition (self-review clause)", None,
        "Studying its own agent baselines, the source reports failures of LLM self-evaluation "
        "as an open problem in building research agents — the checking is done by the same "
        "model that produced the output.",
    ),
    "2409.05258": (
        "qualifies", "R-conservative-supports", "supports",
        "The framework has an LLM propose components that are then validated and evaluated "
        "against existing baselines, a check separate from the proposer, but the excerpt "
        "reports no result at all, so whether this is established behaviour or a proposal is "
        "unsettled between supports and qualifies and the conservative rule chose qualifies.",
    ),
    "2410.01440": (
        None, "R-undecidable-is-a-finding", None,
        "The excerpt states the refinement signal disjunctively — feedback 'from the "
        "environment (or an internal world model)' — so whether the check is external to the "
        "producing component or internal to it is not carried by the excerpt, and "
        "R-excerpt-only forbids supplying it.",
    ),
    "2501.16961": (
        "qualifies", "qualifies definition", None,
        "Instantiations generated by the model are verified by a logical solver, a checker "
        "plainly separate from the producer, but the source fences its own evidence to open "
        "reasoning benchmarks and to 'a significant coverage of cases'.",
    ),
    "2502.19613": (
        "contradicts", "contradicts definition (self-review clause)", None,
        "The source's own system has a single model evaluate the correctness of its own "
        "outputs 'without external feedback', which is self-review and so a denial of "
        "independence.",
    ),
    "2503.22444": (
        "contextualizes", "contextualizes definition", None,
        "The excerpt envisions an autonomous generalist scientist and hypothesises scaling "
        "laws for it; it describes a prospective field rather than reporting a system's "
        "behaviour, so it establishes no position of the source's own.",
    ),
    "2505.12501": (
        None, "R-undecidable-is-a-finding", None,
        "The excerpt names 'absence of self-verification' as one of four deficits the system "
        "tackles but never says what performs verification in it, so the criteria — which turn "
        "on who checks whom — have nothing in the excerpt to decide on.",
    ),
    "2505.19897": (
        "contextualizes", "contextualizes definition", None,
        "The source builds an environment and a human-curated benchmark and reports a 15% "
        "agent success rate; the checking described is the benchmark's, not the agents'.",
    ),
    "2505.21034": (
        "qualifies", "qualifies definition", None,
        "Candidate algorithms written by the LLM are scored inside the loop by an external "
        "benchmark suite rather than by the model that wrote them, but the evidence is fenced "
        "to Bayesian-optimisation algorithm design on BBOB.",
    ),
    "2505.21935": (
        "contextualizes", "R-own-evidence", None,
        "The excerpt is a survey synthesising existing work on hypothesis generation and "
        "validation; what it reports of others is not evidence for the claim, and it "
        "establishes nothing of its own.",
    ),
    "2506.02918": (
        "contradicts", "contradicts definition (self-review clause)", None,
        "Self-verification sampling is driven by the model's own internal environment model, "
        "so the component that checks an output is the one that produced it.",
    ),
    "2506.08968": (
        "qualifies", "qualifies definition", None,
        "Labels proposed by the LLM are re-evaluated by a different signal — CLIP embeddings, "
        "frequency voting and k-nearest-neighbour re-labelling — a checker separate from the "
        "proposer, but the evidence reaches only open-world object annotation.",
    ),
    "2506.11237": (
        "qualifies", "qualifies definition", None,
        "Generated Bash is judged by an LLM judge whose verdicts are themselves measured "
        "against execution-based ground truth, a check independent of the generator, but the "
        "evidence reaches only incident-remediation code in IT automation.",
    ),
    "2506.11442": (
        "contradicts", "contradicts definition (self-review clause)", None,
        "Verification is optimised into the same model that generates the code and runs on "
        "tests the model constructs itself, so the checker is the producer even though a tool "
        "executes the self-written tests.",
    ),
    "2507.10590": (
        "qualifies", "qualifies definition", None,
        "Outputs are checked against programmatic constraints that are not the language model "
        "producing them, but the evidence reaches only pipelines caught in "
        "competing-soft-constraint backtracking loops.",
    ),
    "2507.17209": (
        "qualifies", "qualifies definition", None,
        "Hypotheses proposed with LLM help are filtered against knowledge-graph evidence and "
        "examined by human experts — checks separate from the proposer — but the system is "
        "explicitly collaborative rather than end-to-end automated, and the evidence is two "
        "case studies and expert interviews.",
    ),
    "2508.11860": (
        "qualifies", "R-conservative-supports", "supports",
        "An Agent-as-a-Judge evaluates constraints on routes the planner produces, and whether "
        "that judge counts as separate from the producer or as the same agentic process "
        "checking itself is not settled by the excerpt, so the conservative rule chose "
        "qualifies over supports.",
    ),
    "2508.15126": (
        "qualifies", "R-conservative-supports", "supports",
        "Papers by AI scientists are reviewed and revised on a platform by other human and AI "
        "scientists and the source's experiments show quality improving; whether review by "
        "peer AI scientists is independent of the producing component or the same process at "
        "one remove is not settled by the excerpt, so the conservative rule chose qualifies.",
    ),
    "2509.03036": (
        "qualifies", "qualifies definition", None,
        "Equations produced by the symbolic-regression algorithm are scored by an LLM term "
        "added to the loss, a checker distinct from the producer, but the evidence is fenced "
        "to three algorithms, three models and three physical dynamics.",
    ),
    "2510.02190": (
        "contextualizes", "contextualizes definition", None,
        "The source builds an evaluation framework for deep research agents and reports their "
        "standing on it; the checking described belongs to the benchmark, not to the agents.",
    ),
    "2510.19949": (
        "contradicts", "contradicts definition (self-review clause)", None,
        "The architecture's self-verification with adaptive recovery is performed by the same "
        "agent that produced the actions it checks.",
    ),
    "2511.04583": (
        "qualifies", "qualifies definition", None,
        "The system's papers are assessed by AI reviewers, by the authors and by an external "
        "venue — checks separate from the producing agent — and the source's own evidence is "
        "that the automated part scored well while the human and venue reviews found "
        "limitations, which narrows rather than establishes the claim.",
    ),
    "2511.13825": (
        "contradicts", "contradicts definition", None,
        "The source's own audit of an autonomous AI scientist against random-gene null models "
        "found one of three hypotheses false and concludes such systems 'require rigorous "
        "auditing' — the system did not establish the standing of its own outputs.",
    ),
    "2511.23436": (
        "qualifies", "qualifies definition", None,
        "A frozen large language model verifies the trainable learner's candidates, a "
        "separation of checker from producer that is explicit, but the system is an agentic "
        "learning framework rather than one automating a research cycle, so the claim is "
        "narrowed to the population the source actually tested.",
    ),
    "2512.11509": (
        "contextualizes", "contextualizes definition", None,
        "The source measures how three hallucination-reduction techniques affect divergent "
        "creativity; one of them is a self-verification method, but the finding concerns "
        "creativity, not who checks whose output.",
    ),
    "2512.18292": (
        "contextualizes", "contextualizes definition", None,
        "The LLM judge annotates human negotiation transcripts rather than the outputs of the "
        "system that produced them, so the excerpt bears on automated judging without taking a "
        "position on the claim.",
    ),
    "2512.22145": (
        "qualifies", "qualifies definition", None,
        "Reviews generated by frontier models — a check separate from the papers' authors — "
        "correlate only weakly with human reviewers and carry a systematic overestimation "
        "bias, which the source reads as useful for pre-review screening but not for "
        "autonomous review: the claim holds only in that narrowed role.",
    ),
    "2601.00828": (
        "contradicts", "contradicts definition (self-review clause)", None,
        "The source's own cross-model experiments concern models correcting their own outputs "
        "without external feedback and find the capability weak and inverted in model "
        "strength; the checker is the producer.",
    ),
    "2601.03315": (
        "contradicts", "contradicts definition (self-review clause)", None,
        "Four end-to-end autonomous research attempts by the source's own pipeline yield six "
        "failure modes, one of them 'overexcitement that declares success despite obvious "
        "failures' — the system's own assessment of its outputs, and it failed.",
    ),
    "2601.12346": (
        "contextualizes", "contextualizes definition", None,
        "The pipeline that checks citation grounding and text-visual integrity is the "
        "benchmark's, applied to agents from outside; the excerpt reports how well agents "
        "score, not how or whether they check themselves.",
    ),
    "2602.00521": (
        "contextualizes", "contextualizes definition", None,
        "The framework diagnoses the reliability of LLM judges as measurement instruments; it "
        "concerns a checker's stability under prompt variation, not whether an automating "
        "system's checker is separate from its producer.",
    ),
    "2602.04288": (
        "contradicts", "contradicts definition (self-review clause)", None,
        "Across 11 models and 8 tasks the source finds that reflecting on failed attempts "
        "biases later generations toward the same errors, that self-refinement can collapse "
        "into self-deterioration, and that successful self-verification does not eliminate "
        "the effect.",
    ),
    "2602.12639": (
        "qualifies", "qualifies definition", None,
        "Generated legal text is scored by a hybrid method separate from the generator and "
        "anchored to human judgments, but the evidence reaches only Chinese legalese style "
        "over 200 documents.",
    ),
    "2602.18920": (
        "qualifies", "qualifies definition", None,
        "Ideas come from a training loop in which the model predicts, evaluates and refines "
        "its own next idea, while the reported validation comes from automatic and expert "
        "evaluation outside that loop; the independent part of the checking is the expert "
        "evaluation, and it reaches only research ideation.",
    ),
    "2603.11515": (
        "qualifies", "R-conservative-supports", "supports",
        "Designs proposed by the Inverse Design Agent are judged by hydrodynamics simulations "
        "on HPC, a check unambiguously separate from the proposer, but the source calls its "
        "framework general-purpose while fencing its validation to Richtmyer–Meshkov "
        "instability suppression, so whether the assertion is general or fenced is unsettled "
        "and the conservative rule chose qualifies.",
    ),
    "2603.18516": (
        "contextualizes", "contextualizes definition", None,
        "The source constructs an evaluation framework with relevance judgments derived from a "
        "knowledge base; the checking belongs to the benchmark, and the excerpt takes no "
        "position on whether the agents check themselves.",
    ),
    "2603.20262": (
        "contextualizes", "contextualizes definition", None,
        "The reasoning is inferred from outcome data and the model is then benchmarked on "
        "optimisation tasks; the excerpt reports post-hoc evaluation by the authors rather "
        "than a verification step inside the system.",
    ),
    "2604.00149": (
        "supports", "supports definition", None,
        "The source's own framework integrates programming and scientific verifiers that check "
        "the generating agents' coding correctness and physical validity at each step — a "
        "verification step separate from the component whose output it checks — and the "
        "assertion is made of the framework as such rather than fenced to a subset of its "
        "outputs.",
    ),
    "2604.00248": (
        "contextualizes", "contextualizes definition", None,
        "The correspondence-aware rewards shape how reviews are generated; the excerpt reports "
        "review quality against baselines and takes no position on who checks the system's "
        "outputs.",
    ),
    "2604.03553": (
        "contextualizes", "contextualizes definition", None,
        "The excerpt reports benchmark accuracy measured by the authors on three corpora and a "
        "tool that facilitates evaluation by historians; no checking arrangement internal to "
        "the system is described.",
    ),
    "2604.17406": (
        "contradicts", "contradicts definition (self-review clause)", None,
        "The framework's agents refine hypotheses and self-critique across experimental cycles, "
        "so the component that judges an output is the one that produced it, however well the "
        "framework scores on ten benchmarks.",
    ),
    "2604.18418": (
        "contextualizes", "contextualizes definition", None,
        "The fine-grained evidence verification is the benchmark's instrument applied to 17 "
        "systems from outside; the excerpt reports gaps in their outputs, not the arrangement "
        "by which they check themselves.",
    ),
    "2604.20441": (
        "qualifies", "qualifies definition", None,
        "An audit framework external to the skills it grades reaches ICC 0.449 against expert "
        "consensus, above the human inter-rater baseline — independent checking, quantified — "
        "but fenced to 75 skills in five categories, with one category showing negative "
        "agreement.",
    ),
    "2605.06177": (
        "contextualizes", "contextualizes definition", None,
        "The source addresses reproducibility of agent comparison by supplying a shared "
        "evaluation harness; the checking is the arena's, and the excerpt takes no position on "
        "whether the agents verify their own outputs.",
    ),
    "2605.23273": (
        "qualifies", "qualifies definition", None,
        "Six agents divide problem formulation, validation, execution and quality assessment, "
        "so a design is graded by agents and by a numerical run other than the one that "
        "proposed it, but the evidence reaches only topology-optimisation problems and is "
        "strongest where the model's prior exposure is sparse.",
    ),
    "2605.26730": (
        "qualifies", "qualifies definition", None,
        "Automated reviewers — checkers separate from the papers' authors — match or beat "
        "humans on individual dimensions while no system matches the human baseline across all "
        "of them, so the claim holds within named dimensions and not as a whole.",
    ),
    "2606.04228": (
        "contextualizes", "contextualizes definition", None,
        "The source measures which representation carries more task-relevant information and "
        "identifies a splitting artefact that inflates results; it bears on how AI-for-science "
        "systems choose, not on who verifies their outputs.",
    ),
    "2606.07591": (
        "contextualizes", "contextualizes definition", None,
        "The source reports that end-to-end autonomous research capability is hard to verify "
        "and builds an external rubric-based benchmark to do it; the verification described is "
        "the benchmark's, not the agents'.",
    ),
    "2606.10402": (
        "qualifies", "R-conservative-supports", "supports",
        "Every open problem on the platform carries a verifier that is not the submitting "
        "agent, and twelve verified new state-of-the-art results are the source's own "
        "evidence; but the source fences its scope to mathematical tasks 'where progress can "
        "be measured unambiguously', so whether the assertion is general or fenced is "
        "unsettled and the conservative rule chose qualifies.",
    ),
    "2606.28756": (
        "contextualizes", "contextualizes definition", None,
        "The proposal is an identifier making AI authorship machine-readable; it concerns "
        "provenance and attribution rather than whether a system's outputs are checked by "
        "something other than their producer.",
    ),
    "2607.03863": (
        None, "R-undecidable-is-a-finding", None,
        "The excerpt reports that the Research Execution Plan compiles 'verification "
        "checkpoints' and that the system outperforms baselines at verification, but never "
        "says what performs a check relative to the component whose artefact is checked — "
        "which is the only thing the criteria decide on.",
    ),
    "2607.09195": (
        "qualifies", "qualifies definition", None,
        "The source's own evidence is that a protocol-equipped agent runs an explicit, "
        "auditable hypothesis–test–evidence–belief cycle on materials-science tasks, which "
        "narrows the claim to agents carrying the harness; its stronger premise, that current "
        "agents' processes are unauditable, is asserted rather than shown.",
    ),
    "2607.10127": (
        "qualifies", "qualifies definition", None,
        "Programs mutated by the language model are scored by an evaluation reward outside the "
        "model and used to update it, a check separate from the producer, but the evidence "
        "reaches only symbolic regression for nonlinear oscillator systems.",
    ),
    "2607.22553": (
        "qualifies", "qualifies definition", None,
        "Automated review agrees best with human judgment when given official conference "
        "guidelines and degrades under strict rubric scoring, so the source's evidence makes "
        "the automated check's standing conditional on the guidance it is given.",
    ),
    "2607.26064": (
        "contradicts", "contradicts definition", None,
        "The source argues from the widening gap between agentic scientific output and the "
        "capacity to check it that autonomous agents produce 'experimental results that no "
        "person can verify' — a denial of the claim, argued rather than measured, which this "
        "rationale records.",
    ),
}

NOTES = (
    "Produced blind: the labeller had no access to the classifications being measured, and "
    "the commission file it read carries no labels (verified — the union of case keys is "
    "case_id, claim_text, excerpt, excerpt_sha256, source_identifiers, source_url, title). "
    "Reading applied: an excerpt engages the claim when the source's own evidence says "
    "whether an automating system's outputs are checked by something other than the component "
    "that produced them. Engaged, general, separate checker -> supports; engaged, checker is "
    "the same model, component or process (or absent) -> contradicts; engaged but fenced to a "
    "stage, a domain outside the research cycle, a configuration or the reach of the source's "
    "own tests -> qualifies; no checking arrangement of the source's own system reported "
    "(survey, taxonomy, infrastructure proposal, vision without a system, or a benchmark "
    "measuring some other property) -> contextualizes. "
    "Three asymmetries in the criteria were applied as written rather than smoothed, and are "
    "argued in the return letter: (a) `supports` carries a generality fence and `contradicts` "
    "carries none, so a fenced self-review contradicts while a fenced independent check only "
    "qualifies; (b) that fence, met by a corpus in which every paper fences its evidence to "
    "its own benchmark, leaves `supports` nearly empty — one case in sixty; (c) the tie-break "
    "runs only between supports and qualifies, so a case torn between contradicts and "
    "qualifies has no cell and leaves no trace. "
    "These labels are not a human gold standard. They were made by a machine practice with "
    "the same responsible human as the commissioning practice, which is a limitation of the "
    "exercise and not a footnote to it. Disagreements should be recorded per case and argued "
    "against the rationales, not averaged."
)


def build() -> dict:
    commission = json.loads(COMMISSION.read_text(encoding="utf-8"))
    criteria = json.loads(CRITERIA.read_text(encoding="utf-8"))

    commission_ids = [c["case_id"] for c in commission["cases"]]
    mine = {f"mbcls-{k}" for k in LABELS}
    missing = sorted(set(commission_ids) - mine)
    extra = sorted(mine - set(commission_ids))
    if missing or extra:
        raise SystemExit(f"case id mismatch — missing: {missing}; extra: {extra}")

    cases = []
    for case in commission["cases"]:
        relation, decided_by, tie_with, text = LABELS[case["case_id"].removeprefix("mbcls-")]
        digest = "sha256:" + hashlib.sha256(case["excerpt"].encode("utf-8")).hexdigest()
        if digest != case["excerpt_sha256"]:
            raise SystemExit(f"{case['case_id']}: excerpt hash does not match the commission")
        entry = {
            "case_id": case["case_id"],
            "excerpt": case["excerpt"],
            "excerpt_sha256": case["excerpt_sha256"],
            "source_identifiers": case["source_identifiers"],
            "claim_text": case["claim_text"],
            "decided_by": decided_by,
            "tie_with": tie_with,
        }
        if relation is None:
            entry["expected_relation"] = None
            entry["expected_rationale"] = None
            entry["undecidable"] = True
            entry["undecidable_reason"] = text
        else:
            entry["expected_relation"] = relation
            entry["expected_rationale"] = text
            entry["undecidable"] = False
            entry["undecidable_reason"] = None
        cases.append(entry)

    return {
        "set_id": "mb-cls-ulysses-v1",
        "categories": commission["categories"],
        "criteria_version": criteria["criteria_version"],
        "criteria_locked_at": criteria["locked_at"],
        "criteria_lock_content_hash": "sha256:"
        + hashlib.sha256(CRITERIA.read_bytes()).hexdigest(),
        "criteria": criteria["definitions"],
        "labelled_at": LABELLED_AT,
        "label_provenance": {
            "producing_practice": "ulysses",
            "account": (
                "Labelled blind by the Ulysses practice on 2026-08-01 against "
                "mb-cls-criteria-v2 as delivered, from the sixty excerpts in commission.v2.json "
                "and nothing else; no access to the classifications being measured. Study "
                "record and the frame used: projects/2026-08-01-sixty-cases-blind/ in the "
                "Ulysses repository."
            ),
            "encounter_id": None,
            "blind_to_measured_labels": True,
        },
        "notes": NOTES,
        "cases": cases,
    }


def main() -> None:
    doc = build()
    payload = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != payload:
            raise SystemExit("mb-cls-ulysses-v1.json is out of date with this script")
        print("label set matches this script")
    else:
        OUT.write_text(payload, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)}")

    counts: dict[str, int] = {}
    for case in doc["cases"]:
        key = "undecidable" if case["undecidable"] else case["expected_relation"]
        counts[key] = counts.get(key, 0) + 1
    ties = sum(1 for c in doc["cases"] if c["tie_with"])
    print("counts:", counts)
    print(f"ties: {ties}/{len(doc['cases'])} = {ties / len(doc['cases']):.1%}")
    print("set sha256:", hashlib.sha256(payload.encode("utf-8")).hexdigest())


if __name__ == "__main__":
    main()
